// import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from 'next/font/google'
// import styles from '~/styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={styles.main}>
//         <div className={styles.description}>
//           <p>
//             Get started by editing&nbsp;
//             <code className={styles.code}>src/pages/index.tsx</code>
//           </p>
//           <div>
//             <a
//               href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               By{' '}
//               <Image
//                 src="/vercel.svg"
//                 alt="Vercel Logo"
//                 className={styles.vercelLogo}
//                 width={100}
//                 height={24}
//                 priority
//               />
//             </a>
//           </div>
//         </div>

//         <div className={styles.center}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js Logo"
//             width={180}
//             height={37}
//             priority
//           />
//           <div className={styles.thirteen}>
//             <Image
//               src="/thirteen.svg"
//               alt="13"
//               width={40}
//               height={31}
//               priority
//             />
//           </div>
//         </div>

//         <div className={styles.grid}>
//           <a
//             href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Docs <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Find in-depth information about Next.js features and&nbsp;API.
//             </p>
//           </a>

//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Learn <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Learn about Next.js in an interactive course with&nbsp;quizzes!
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Templates <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Discover and deploy boilerplate example Next.js&nbsp;projects.
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Deploy <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Instantly deploy your Next.js site to a shareable URL
//               with&nbsp;Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//     </>
//   )
// }
// import Link from 'next/link'

// export default function Home() {
//   const products = [{ name: 'bag' }, { name: 'shoes' }, { name: 'socks' }]

//   return (
//     <div className='p-8'>
//       <ul>
//         <li>
//           <Link href='/start' legacyBehavior>
//             <a>Start</a>
//           </Link>
//         </li>
//         <li>
//           <Link href='/createNew' legacyBehavior>
//             <a>create new</a>
//           </Link>
//         </li>
//         <li>
//           <Link href='/addExisting' legacyBehavior>
//             <a>add existing</a>
//           </Link>
//         </li>
//         <li>
//           <Link href='/dashboard' legacyBehavior>
//             <a>dashboard</a>
//           </Link>
//         </li>
//       </ul>
//     </div>
//   )
// }
// import Image from 'next/image'
// import Link from 'next/link'
import { FC } from 'react';
import { Link } from 'react-router-dom';
import { Button } from '~/components/atoms/Button';
import { IconText } from '~/components/molecules/IconText';
import LastOpenedWallet from '~/components/templates/LastOpenedWallet';
import Topbar from '~/components/templates/Topbar';
import { mockLastOpenedWallets as wallets } from '~/utils/Mock';
import Spacer from '~/utils/Spacer';

export const Home: FC = () => {
  return (
    <div className='w-screen h-screen flex flex-col'>
      <Topbar />

      <div className='flex flex-col justify-center items-center w-full h-full box-border py-8 px-[4.5rem] bg-bgDark'>
        <img
          src='/assets/Meson_start_logo.png'
          alt='Meson Logo'
          width='176'
          height='40'
        />

        <Spacer size={16} axis={'vertical'} />
        <LastOpenedWallet wallets={wallets} />
        <Spacer size={16} axis={'vertical'} />
        <div className='flex flex-row justify-between items-center w-[51rem] '>
          <Link to='/create-new/step1' className='w-full'>
            <Button btnVariant={'special'} btnSize={'sp'} btnType={'button'}>
              <IconText iconType={'CreateNew'} iconColor={'white'}>
                Create new wallet
              </IconText>
            </Button>
          </Link>
          <Link to='/add-existing/step1' className='w-full'>
            <Button btnVariant={'special'} btnSize={'sp'} btnType={'button'}>
              <IconText iconType={'AddExist'} iconColor={'white'}>
                Add existing wallet
              </IconText>
            </Button>
          </Link>
        </div>
      </div>
    </div>
  );
};
