export const currencies = [
  {
    value: 'AED',
    label: 'AED',
    decimals: 2,
    name: 'United Arab Emirates dirham',
    number: '784',
  },
  {
    value: 'AFN',
    label: 'AFN',
    decimals: 2,
    name: 'Afghan afghani',
    number: '971',
  },
  {
    value: 'ALL',
    label: 'ALL',
    decimals: 2,
    name: 'Albanian lek',
    number: '8',
  },
  {
    value: 'AMD',
    label: 'AMD',
    decimals: 2,
    name: 'Armenian dram',
    number: '51',
  },
  {
    value: 'ANG',
    label: 'ANG',
    decimals: 2,
    name: 'Netherlands Antillean guilder',
    number: '532',
  },
  {
    value: 'AOA',
    label: 'AOA',
    decimals: 2,
    name: 'Angolan kwanza',
    number: '973',
  },
  {
    value: 'ARS',
    label: 'ARS',
    decimals: 2,
    name: 'Argentine peso',
    number: '32',
  },
  {
    value: 'AUD',
    label: 'AUD',
    decimals: 2,
    name: 'Australian dollar',
    number: '36',
  },
  {
    value: 'AWG',
    label: 'AWG',
    decimals: 2,
    name: 'Aruban florin',
    number: '533',
  },
  {
    value: 'AZN',
    label: 'AZN',
    decimals: 2,
    name: 'Azerbaijani manat',
    number: '944',
  },
  {
    value: 'BAM',
    label: 'BAM',
    decimals: 2,
    name: 'Bosnia and Herzegovina convertible mark',
    number: '977',
  },
  {
    value: 'BBD',
    label: 'BBD',
    decimals: 2,
    name: 'Barbados dollar',
    number: '52',
  },
  {
    value: 'BDT',
    label: 'BDT',
    decimals: 2,
    name: 'Bangladeshi taka',
    number: '50',
  },
  {
    value: 'BGN',
    label: 'BGN',
    decimals: 2,
    name: 'Bulgarian lev',
    number: '975',
  },
  {
    value: 'BHD',
    label: 'BHD',
    decimals: 3,
    name: 'Bahraini dinar',
    number: '48',
  },
  {
    value: 'BIF',
    label: 'BIF',
    decimals: 0,
    name: 'Burundian franc',
    number: '108',
  },
  {
    value: 'BMD',
    label: 'BMD',
    decimals: 2,
    name: 'Bermudian dollar (customarily known as Bermuda dollar)',
    number: '60',
  },
  {
    value: 'BND',
    label: 'BND',
    decimals: 2,
    name: 'Brunei dollar',
    number: '96',
  },
  {
    value: 'BOB',
    label: 'BOB',
    decimals: 2,
    name: 'Boliviano',
    number: '68',
  },
  {
    value: 'BOV',
    label: 'BOV',
    decimals: 2,
    name: 'Bolivian Mvdol',
    number: '984',
  },
  {
    value: 'BRL',
    label: 'BRL',
    decimals: 2,
    name: 'Brazilian real',
    number: '986',
  },
  {
    value: 'BSD',
    label: 'BSD',
    decimals: 2,
    name: 'Bahamian dollar',
    number: '44',
  },
  {
    value: 'BTN',
    label: 'BTN',
    decimals: 2,
    name: 'Bhutanese ngultrum',
    number: '64',
  },
  {
    value: 'BWP',
    label: 'BWP',
    decimals: 2,
    name: 'Botswana pula',
    number: '72',
  },
  {
    value: 'BYR',
    label: 'BYR',
    decimals: 0,
    name: 'Belarusian ruble',
    number: '974',
  },
  {
    value: 'BZD',
    label: 'BZD',
    decimals: 2,
    name: 'Belize dollar',
    number: '84',
  },
  {
    value: 'CAD',
    label: 'CAD',
    decimals: 2,
    name: 'Canadian dollar',
    number: '124',
  },
  {
    value: 'CDF',
    label: 'CDF',
    decimals: 2,
    name: 'Congolese franc',
    number: '976',
  },
  {
    value: 'CHE',
    label: 'CHE',
    decimals: 2,
    name: 'WIR Euro (complementary currency)',
    number: '947',
  },
  {
    value: 'CHF',
    label: 'CHF',
    decimals: 2,
    name: 'Swiss franc',
    number: '756',
  },
  {
    value: 'CHW',
    label: 'CHW',
    decimals: 2,
    name: 'WIR Franc (complementary currency)',
    number: '948',
  },
  {
    value: 'CLF',
    label: 'CLF',
    decimals: 0,
    name: 'Unidad de Fomento',
    number: '990',
  },
  {
    value: 'CLP',
    label: 'CLP',
    decimals: 0,
    name: 'Chilean peso',
    number: '152',
  },
  {
    value: 'CNY',
    label: 'CNY',
    decimals: 2,
    name: 'Chinese yuan',
    number: '156',
  },
  {
    value: 'COP',
    label: 'COP',
    decimals: 2,
    name: 'Colombian peso',
    number: '170',
  },
  {
    value: 'COU',
    label: 'COU',
    decimals: 2,
    name: 'Unidad de Valor Real',
    number: '970',
  },
  {
    value: 'CRC',
    label: 'CRC',
    decimals: 2,
    name: 'Costa Rican colon',
    number: '188',
  },
  {
    value: 'CUC',
    label: 'CUC',
    decimals: 2,
    name: 'Cuban convertible peso',
    number: '931',
  },
  {
    value: 'CUP',
    label: 'CUP',
    decimals: 2,
    name: 'Cuban peso',
    number: '192',
  },
  {
    value: 'CVE',
    label: 'CVE',
    decimals: 0,
    name: 'Cape Verde escudo',
    number: '132',
  },
  {
    value: 'CZK',
    label: 'CZK',
    decimals: 2,
    name: 'Czech koruna',
    number: '203',
  },
  {
    value: 'DJF',
    label: 'DJF',
    decimals: 0,
    name: 'Djiboutian franc',
    number: '262',
  },
  {
    value: 'DKK',
    label: 'DKK',
    decimals: 2,
    name: 'Danish krone',
    number: '208',
  },
  {
    value: 'DOP',
    label: 'DOP',
    decimals: 2,
    name: 'Dominican peso',
    number: '214',
  },
  {
    value: 'DZD',
    label: 'DZD',
    decimals: 2,
    name: 'Algerian dinar',
    number: '12',
  },
  {
    value: 'EGP',
    label: 'EGP',
    decimals: 2,
    name: 'Egyptian pound',
    number: '818',
  },
  {
    value: 'ERN',
    label: 'ERN',
    decimals: 2,
    name: 'Eritrean nakfa',
    number: '232',
  },
  {
    value: 'ETB',
    label: 'ETB',
    decimals: 2,
    name: 'Ethiopian birr',
    number: '230',
  },
  {
    value: 'EUR',
    label: 'EUR',
    decimals: 2,
    name: 'Euro',
    number: '978',
  },
  {
    value: 'FJD',
    label: 'FJD',
    decimals: 2,
    name: 'Fiji dollar',
    number: '242',
  },
  {
    value: 'FKP',
    label: 'FKP',
    decimals: 2,
    name: 'Falkland Islands pound',
    number: '238',
  },
  {
    value: 'GBP',
    label: 'GBP',
    decimals: 2,
    name: 'Pound sterling',
    number: '826',
  },
  {
    value: 'GEL',
    label: 'GEL',
    decimals: 2,
    name: 'Georgian lari',
    number: '981',
  },
  {
    value: 'GHS',
    label: 'GHS',
    decimals: 2,
    name: 'Ghanaian cedi',
    number: '936',
  },
  {
    value: 'GIP',
    label: 'GIP',
    decimals: 2,
    name: 'Gibraltar pound',
    number: '292',
  },
  {
    value: 'GMD',
    label: 'GMD',
    decimals: 2,
    name: 'Gambian dalasi',
    number: '270',
  },
  {
    value: 'GNF',
    label: 'GNF',
    decimals: 0,
    name: 'Guinean franc',
    number: '324',
  },
  {
    value: 'GTQ',
    label: 'GTQ',
    decimals: 2,
    name: 'Guatemalan quetzal',
    number: '320',
  },
  {
    value: 'GYD',
    label: 'GYD',
    decimals: 2,
    name: 'Guyanese dollar',
    number: '328',
  },
  {
    value: 'HKD',
    label: 'HKD',
    decimals: 2,
    name: 'Hong Kong dollar',
    number: '344',
  },
  {
    value: 'HNL',
    label: 'HNL',
    decimals: 2,
    name: 'Honduran lempira',
    number: '340',
  },
  {
    value: 'HRK',
    label: 'HRK',
    decimals: 2,
    name: 'Croatian kuna',
    number: '191',
  },
  {
    value: 'HTG',
    label: 'HTG',
    decimals: 2,
    name: 'Haitian gourde',
    number: '332',
  },
  {
    value: 'HUF',
    label: 'HUF',
    decimals: 2,
    name: 'Hungarian forint',
    number: '348',
  },
  {
    value: 'IDR',
    label: 'IDR',
    decimals: 2,
    name: 'Indonesian rupiah',
    number: '360',
  },
  {
    value: 'ILS',
    label: 'ILS',
    decimals: 2,
    name: 'Israeli new shekel',
    number: '376',
  },
  {
    value: 'INR',
    label: 'INR',
    decimals: 2,
    name: 'Indian rupee',
    number: '356',
  },
  {
    value: 'IQD',
    label: 'IQD',
    decimals: 3,
    name: 'Iraqi dinar',
    number: '368',
  },
  {
    value: 'IRR',
    label: 'IRR',
    decimals: 0,
    name: 'Iranian rial',
    number: '364',
  },
  {
    value: 'ISK',
    label: 'ISK',
    decimals: 0,
    name: 'Icelandic króna',
    number: '352',
  },
  {
    value: 'JMD',
    label: 'JMD',
    decimals: 2,
    name: 'Jamaican dollar',
    number: '388',
  },
  {
    value: 'JOD',
    label: 'JOD',
    decimals: 3,
    name: 'Jordanian dinar',
    number: '400',
  },
  {
    value: 'JPY',
    label: 'JPY',
    decimals: 0,
    name: 'Japanese yen',
    number: '392',
  },
  {
    value: 'KES',
    label: 'KES',
    decimals: 2,
    name: 'Kenyan shilling',
    number: '404',
  },
  {
    value: 'KGS',
    label: 'KGS',
    decimals: 2,
    name: 'Kyrgyzstani som',
    number: '417',
  },
  {
    value: 'KHR',
    label: 'KHR',
    decimals: 2,
    name: 'Cambodian riel',
    number: '116',
  },
  {
    value: 'KMF',
    label: 'KMF',
    decimals: 0,
    name: 'Comoro franc',
    number: '174',
  },
  {
    value: 'KPW',
    label: 'KPW',
    decimals: 0,
    name: 'North Korean won',
    number: '408',
  },
  {
    value: 'KRW',
    label: 'KRW',
    decimals: 0,
    name: 'South Korean won',
    number: '410',
  },
  {
    value: 'KWD',
    label: 'KWD',
    decimals: 3,
    name: 'Kuwaiti dinar',
    number: '414',
  },
  {
    value: 'KYD',
    label: 'KYD',
    decimals: 2,
    name: 'Cayman Islands dollar',
    number: '136',
  },
  {
    value: 'KZT',
    label: 'KZT',
    decimals: 2,
    name: 'Kazakhstani tenge',
    number: '398',
  },
  {
    value: 'LAK',
    label: 'LAK',
    decimals: 0,
    name: 'Lao kip',
    number: '418',
  },
  {
    value: 'LBP',
    label: 'LBP',
    decimals: 0,
    name: 'Lebanese pound',
    number: '422',
  },
  {
    value: 'LKR',
    label: 'LKR',
    decimals: 2,
    name: 'Sri Lankan rupee',
    number: '144',
  },
  {
    value: 'LRD',
    label: 'LRD',
    decimals: 2,
    name: 'Liberian dollar',
    number: '430',
  },
  {
    value: 'LSL',
    label: 'LSL',
    decimals: 2,
    name: 'Lesotho loti',
    number: '426',
  },
  {
    value: 'LTL',
    label: 'LTL',
    decimals: 2,
    name: 'Lithuanian litas',
    number: '440',
  },
  {
    value: 'LVL',
    label: 'LVL',
    decimals: 2,
    name: 'Latvian lats',
    number: '428',
  },
  {
    value: 'LYD',
    label: 'LYD',
    decimals: 3,
    name: 'Libyan dinar',
    number: '434',
  },
  {
    value: 'MAD',
    label: 'MAD',
    decimals: 2,
    name: 'Moroccan dirham',
    number: '504',
  },
  {
    value: 'MDL',
    label: 'MDL',
    decimals: 2,
    name: 'Moldovan leu',
    number: '498',
  },
  {
    value: 'MGA',
    label: 'MGA',
    decimals: 0,
    name: 'Malagasy ariary',
    number: '969',
  },
  {
    value: 'MKD',
    label: 'MKD',
    decimals: 0,
    name: 'Macedonian denar',
    number: '807',
  },
  {
    value: 'MMK',
    label: 'MMK',
    decimals: 0,
    name: 'Myanma kyat',
    number: '104',
  },
  {
    value: 'MNT',
    label: 'MNT',
    decimals: 2,
    name: 'Mongolian tugrik',
    number: '496',
  },
  {
    value: 'MOP',
    label: 'MOP',
    decimals: 2,
    name: 'Macanese pataca',
    number: '446',
  },
  {
    value: 'MRO',
    label: 'MRO',
    decimals: 0,
    name: 'Mauritanian ouguiya',
    number: '478',
  },
  {
    value: 'MUR',
    label: 'MUR',
    decimals: 2,
    name: 'Mauritian rupee',
    number: '480',
  },
  {
    value: 'MVR',
    label: 'MVR',
    decimals: 2,
    name: 'Maldivian rufiyaa',
    number: '462',
  },
  {
    value: 'MWK',
    label: 'MWK',
    decimals: 2,
    name: 'Malawian kwacha',
    number: '454',
  },
  {
    value: 'MXN',
    label: 'MXN',
    decimals: 2,
    name: 'Mexican peso',
    number: '484',
  },
  {
    value: 'MXV',
    label: 'MXV',
    decimals: 2,
    name: 'Mexican Unidad de Inversion (UDI)',
    number: '979',
  },
  {
    value: 'MYR',
    label: 'MYR',
    decimals: 2,
    name: 'Malaysian ringgit',
    number: '458',
  },
  {
    value: 'MZN',
    label: 'MZN',
    decimals: 2,
    name: 'Mozambican metical',
    number: '943',
  },
  {
    value: 'NAD',
    label: 'NAD',
    decimals: 2,
    name: 'Namibian dollar',
    number: '516',
  },
  {
    value: 'NGN',
    label: 'NGN',
    decimals: 2,
    name: 'Nigerian naira',
    number: '566',
  },
  {
    value: 'NIO',
    label: 'NIO',
    decimals: 2,
    name: 'Nicaraguan córdoba',
    number: '558',
  },
  {
    value: 'NOK',
    label: 'NOK',
    decimals: 2,
    name: 'Norwegian krone',
    number: '578',
  },
  {
    value: 'NPR',
    label: 'NPR',
    decimals: 2,
    name: 'Nepalese rupee',
    number: '524',
  },
  {
    value: 'NZD',
    label: 'NZD',
    decimals: 2,
    name: 'New Zealand dollar',
    number: '554',
  },
  {
    value: 'OMR',
    label: 'OMR',
    decimals: 3,
    name: 'Omani rial',
    number: '512',
  },
  {
    value: 'PAB',
    label: 'PAB',
    decimals: 2,
    name: 'Panamanian balboa',
    number: '590',
  },
  {
    value: 'PEN',
    label: 'PEN',
    decimals: 2,
    name: 'Peruvian nuevo sol',
    number: '604',
  },
  {
    value: 'PGK',
    label: 'PGK',
    decimals: 2,
    name: 'Papua New Guinean kina',
    number: '598',
  },
  {
    value: 'PHP',
    label: 'PHP',
    decimals: 2,
    name: 'Philippine peso',
    number: '608',
  },
  {
    value: 'PKR',
    label: 'PKR',
    decimals: 2,
    name: 'Pakistani rupee',
    number: '586',
  },
  {
    value: 'PLN',
    label: 'PLN',
    decimals: 2,
    name: 'Polish złoty',
    number: '985',
  },
  {
    value: 'PYG',
    label: 'PYG',
    decimals: 0,
    name: 'Paraguayan guaraní',
    number: '600',
  },
  {
    value: 'QAR',
    label: 'QAR',
    decimals: 2,
    name: 'Qatari riyal',
    number: '634',
  },
  {
    value: 'RON',
    label: 'RON',
    decimals: 2,
    name: 'Romanian new leu',
    number: '946',
  },
  {
    value: 'RSD',
    label: 'RSD',
    decimals: 2,
    name: 'Serbian dinar',
    number: '941',
  },
  {
    value: 'RUB',
    label: 'RUB',
    decimals: 2,
    name: 'Russian rouble',
    number: '643',
  },
  {
    value: 'RWF',
    label: 'RWF',
    decimals: 0,
    name: 'Rwandan franc',
    number: '646',
  },
  {
    value: 'SAR',
    label: 'SAR',
    decimals: 2,
    name: 'Saudi riyal',
    number: '682',
  },
  {
    value: 'SBD',
    label: 'SBD',
    decimals: 2,
    name: 'Solomon Islands dollar',
    number: '90',
  },
  {
    value: 'SCR',
    label: 'SCR',
    decimals: 2,
    name: 'Seychelles rupee',
    number: '690',
  },
  {
    value: 'SDG',
    label: 'SDG',
    decimals: 2,
    name: 'Sudanese pound',
    number: '938',
  },
  {
    value: 'SEK',
    label: 'SEK',
    decimals: 2,
    name: 'Swedish krona/kronor',
    number: '752',
  },
  {
    value: 'SGD',
    label: 'SGD',
    decimals: 2,
    name: 'Singapore dollar',
    number: '702',
  },
  {
    value: 'SHP',
    label: 'SHP',
    decimals: 2,
    name: 'Saint Helena pound',
    number: '654',
  },
  {
    value: 'SLL',
    label: 'SLL',
    decimals: 0,
    name: 'Sierra Leonean leone',
    number: '694',
  },
  {
    value: 'SOS',
    label: 'SOS',
    decimals: 2,
    name: 'Somali shilling',
    number: '706',
  },
  {
    value: 'SRD',
    label: 'SRD',
    decimals: 2,
    name: 'Surinamese dollar',
    number: '968',
  },
  {
    value: 'SSP',
    label: 'SSP',
    decimals: 2,
    name: 'South Sudanese pound',
    number: '728',
  },
  {
    value: 'STD',
    label: 'STD',
    decimals: 0,
    name: 'São Tomé and Príncipe dobra',
    number: '678',
  },
  {
    value: 'SYP',
    label: 'SYP',
    decimals: 2,
    name: 'Syrian pound',
    number: '760',
  },
  {
    value: 'SZL',
    label: 'SZL',
    decimals: 2,
    name: 'Swazi lilangeni',
    number: '748',
  },
  {
    value: 'THB',
    label: 'THB',
    decimals: 2,
    name: 'Thai baht',
    number: '764',
  },
  {
    value: 'TJS',
    label: 'TJS',
    decimals: 2,
    name: 'Tajikistani somoni',
    number: '972',
  },
  {
    value: 'TMT',
    label: 'TMT',
    decimals: 2,
    name: 'Turkmenistani manat',
    number: '934',
  },
  {
    value: 'TND',
    label: 'TND',
    decimals: 3,
    name: 'Tunisian dinar',
    number: '788',
  },
  {
    value: 'TOP',
    label: 'TOP',
    decimals: 2,
    name: 'Tongan paʻanga',
    number: '776',
  },
  {
    value: 'TRY',
    label: 'TRY',
    decimals: 2,
    name: 'Turkish lira',
    number: '949',
  },
  {
    value: 'TTD',
    label: 'TTD',
    decimals: 2,
    name: 'Trinidad and Tobago dollar',
    number: '780',
  },
  {
    value: 'TWD',
    label: 'TWD',
    decimals: 2,
    name: 'New Taiwan dollar',
    number: '901',
  },
  {
    value: 'TZS',
    label: 'TZS',
    decimals: 2,
    name: 'Tanzanian shilling',
    number: '834',
  },
  {
    value: 'UAH',
    label: 'UAH',
    decimals: 2,
    name: 'Ukrainian hryvnia',
    number: '980',
  },
  {
    value: 'UGX',
    label: 'UGX',
    decimals: 2,
    name: 'Ugandan shilling',
    number: '800',
  },
  {
    value: 'USD',
    label: 'USD',
    decimals: 2,
    name: 'United States dollar',
    number: '840',
  },
  {
    value: 'USN',
    label: 'USN',
    decimals: 2,
    name: 'United States dollar (next day)',
    number: '997',
  },
  {
    value: 'USS',
    label: 'USS',
    decimals: 2,
    name: 'United States dollar (same day) (one source[who?] claims it is no longer used, but it is still on the ISO 4217-MA list)',
    number: '998',
  },
  {
    value: 'UYI',
    label: 'UYI',
    decimals: 0,
    name: 'Uruguay Peso en Unidades Indexadas (URUIURUI)',
    number: '940',
  },
  {
    value: 'UYU',
    label: 'UYU',
    decimals: 2,
    name: 'Uruguayan peso',
    number: '858',
  },
  {
    value: 'UZS',
    label: 'UZS',
    decimals: 2,
    name: 'Uzbekistan som',
    number: '860',
  },
  {
    value: 'VEF',
    label: 'VEF',
    decimals: 2,
    name: 'Venezuelan bolívar fuerte',
    number: '937',
  },
  {
    value: 'VND',
    label: 'VND',
    decimals: 0,
    name: 'Vietnamese dong',
    number: '704',
  },
  {
    value: 'VUV',
    label: 'VUV',
    decimals: 0,
    name: 'Vanuatu vatu',
    number: '548',
  },
  {
    value: 'WST',
    label: 'WST',
    decimals: 2,
    name: 'Samoan tala',
    number: '882',
  },
  {
    value: 'XAF',
    label: 'XAF',
    decimals: 0,
    name: 'CFA franc BEAC',
    number: '950',
  },
  {
    value: 'XAG',
    label: 'XAG',
    decimals: null,
    name: 'Silver (one troy ounce)',
    number: '961',
  },
  {
    value: 'XAU',
    label: 'XAU',
    decimals: null,
    name: 'Gold (one troy ounce)',
    number: '959',
  },
  {
    value: 'XBA',
    label: 'XBA',
    decimals: null,
    name: 'European Composite Unit (EURCO) (bond market unit)',
    number: '955',
  },
  {
    value: 'XBB',
    label: 'XBB',
    decimals: null,
    name: 'European Monetary Unit (E.M.U.-6) (bond market unit)',
    number: '956',
  },
  {
    value: 'XBC',
    label: 'XBC',
    decimals: null,
    name: 'European Unit of Account 9 (E.U.A.-9) (bond market unit)',
    number: '957',
  },
  {
    value: 'XBD',
    label: 'XBD',
    decimals: null,
    name: 'European Unit of Account 17 (E.U.A.-17) (bond market unit)',
    number: '958',
  },
  {
    value: 'XCD',
    label: 'XCD',
    decimals: 2,
    name: 'East Caribbean dollar',
    number: '951',
  },
  {
    value: 'XDR',
    label: 'XDR',
    decimals: null,
    name: 'Special drawing rights',
    number: '960',
  },
  {
    value: 'XFU',
    label: 'XFU',
    decimals: null,
    name: 'UIC franc (special settlement currency)',
    number: 'Nil',
  },
  {
    value: 'XOF',
    label: 'XOF',
    decimals: 0,
    name: 'CFA franc BCEAO',
    number: '952',
  },
  {
    value: 'XPD',
    label: 'XPD',
    decimals: null,
    name: 'Palladium (one troy ounce)',
    number: '964',
  },
  {
    value: 'XPF',
    label: 'XPF',
    decimals: 0,
    name: 'CFP franc',
    number: '953',
  },
  {
    value: 'XPT',
    label: 'XPT',
    decimals: null,
    name: 'Platinum (one troy ounce)',
    number: '962',
  },
  {
    value: 'XXX',
    label: 'XXX',
    decimals: null,
    name: 'No currency',
    number: '999',
  },
  {
    value: 'YER',
    label: 'YER',
    decimals: 2,
    name: 'Yemeni rial',
    number: '886',
  },
  {
    value: 'ZAR',
    label: 'ZAR',
    decimals: 2,
    name: 'South African rand',
    number: '710',
  },
  {
    value: 'ZMW',
    label: 'ZMW',
    decimals: 2,
    name: 'Zambian kwacha',
    number: '967',
  },
]
